@extends('layouts.main')

@section('content')
  <div class="card card-md">
    <div class="card-body">
      <h3 class="card-title">Terms of service</h3>
      <div class="markdown">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>
        <hr />
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>
        <h3 id="1-tablerio">1. Banking App</h3>
        <ul>
          <li>
            <p><strong>Responsibility of Contributors.</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>
          </li>
          <li>
            <p><strong>HTTPS.</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>
          </li>
        </ul>
        <h3 id="2-responsibility-of-visitors">2. Responsibility of Visitors.</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>

        <h3 id="3-content-posted-on-other-websites">3. Content Posted on Other Websites.</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>

        <h3 id="5-copyright-infringement-and-dmca-policy">5. Copyright Infringement and DMCA Policy.</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>

        <h3 id="6-intellectual-property">6. Intellectual Property.</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque laoreet suspendisse interdum consectetur. Cursus vitae congue mauris rhoncus aenean vel elit. Nunc scelerisque viverra mauris in aliquam sem. Pulvinar mattis nunc sed blandit libero volutpat sed. Sagittis nisl rhoncus mattis rhoncus. Et malesuada fames ac turpis egestas sed tempus urna et. Scelerisque in dictum non consectetur a. Vulputate ut pharetra sit amet aliquam. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sit amet cursus sit amet dictum sit amet. Morbi tincidunt ornare massa eget. Eleifend mi in nulla posuere sollicitudin aliquam. Et tortor consequat id porta nibh venenatis cras. Cursus risus at ultrices mi tempus imperdiet. Dui id ornare arcu odio ut sem nulla pharetra diam. Laoreet non curabitur gravida arcu ac tortor dignissim.</p>
      </div>
    </div>
  </div>
    
@endsection